// src/api/base44Client.js — generated by unvibe.
//
// Re-exports the local `db` so the rest of your codebase keeps its existing
// imports (`import { db } from '@/api/base44Client'`) without any edits.

export { db, auth, entities, integrations } from '@/lib/localDb.js';
export { db as base44 } from '@/lib/localDb.js';
export { db as default } from '@/lib/localDb.js';
