// src/api/entities.js — generated by unvibe.
//
// Individual named exports for every entity. Matches the shape some Base44 apps
// import from (`import { Card, Deck } from '@/api/entities'`) while still
// backing onto the same underlying local store.

import { entities } from '@/lib/localDb.js';

// PLACEHOLDER: replaced at codemod time with one export per entity.
// export const Card = entities.Card;
// export const Deck = entities.Deck;
