// @unvibe/codemods-base44
//
// Pure, deterministic transforms that take a FileMap (as produced by
// @unvibe/detect) and return a new FileMap representing a clean,
// runnable project. The orchestrator is `transformProject`; individual
// step helpers are exported so they're easy to test in isolation.

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { detectFromFileMap } from '@unvibe/detect';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SHIM_ROOT = resolve(__dirname, '../../../shim-lib/localDb/src');

/**
 * @typedef {import('@unvibe/detect').DetectionReport} DetectionReport
 */

/**
 * @typedef {Object} TransformOptions
 * @property {'localDb'} [target='localDb']    Which runtime shim to inject. Only localDb in v1.
 * @property {string}    [projectName]         Human-friendly name for package.json + README.
 * @property {string}    [projectSlug]         Slug used for the `name` field in package.json.
 */

/**
 * @typedef {Object} TransformResult
 * @property {import('@unvibe/detect').FileMap} files   Rewritten project tree.
 * @property {string[]} changes                               Human-readable summary of what was changed.
 * @property {DetectionReport} report                          Detection report used to drive the transforms.
 */

/**
 * Top-level orchestrator. Runs detection (if no report is provided), applies
 * every transform, and returns a new FileMap plus a change log suitable for
 * displaying to the user.
 *
 * @param {import('@unvibe/detect').FileMap} files
 * @param {TransformOptions} [options]
 * @returns {TransformResult}
 */
export function transformProject(files, options = {}) {
  const report = detectFromFileMap(files);
  const changes = [];
  const opts = {
    target: options.target ?? 'localDb',
    projectName: options.projectName ?? inferProjectName(files),
    projectSlug: options.projectSlug ?? inferProjectSlug(files),
  };

  /** @type {import('@unvibe/detect').FileMap} */
  const out = { ...files };

  transformPackageJson(out, opts, changes);
  transformViteConfig(out, changes);
  rewriteBase44Client(out, report, changes);
  injectLocalDbShim(out, report, changes);
  injectEntitiesModule(out, report, changes);
  transformAppParams(out, changes);
  transformIndexHtml(out, opts, changes);
  transformReadme(out, opts, report, changes);
  generateEnvExample(out, report, changes);

  return { files: out, changes, report };
}

// ---------- package.json ----------

export function transformPackageJson(files, opts, changes) {
  const raw = readText(files['package.json']);
  if (!raw) return;
  const pkg = JSON.parse(raw);

  for (const name of ['@base44/sdk', '@base44/vite-plugin']) {
    if (pkg.dependencies?.[name]) {
      delete pkg.dependencies[name];
      changes.push(`Removed \`${name}\` from package.json dependencies.`);
    }
    if (pkg.devDependencies?.[name]) {
      delete pkg.devDependencies[name];
      changes.push(`Removed \`${name}\` from package.json devDependencies.`);
    }
  }

  if (pkg.name === 'base44-app' || !pkg.name) {
    pkg.name = opts.projectSlug;
    changes.push(`Renamed package to \`${opts.projectSlug}\`.`);
  }

  files['package.json'] = JSON.stringify(pkg, null, 2) + '\n';
}

// ---------- vite.config.js ----------

const CLEAN_VITE_CONFIG = `import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';
import path from 'node:path';

// Generated by unvibe. The original vite.config.js called the
// \`@base44/vite-plugin\` which is no longer available post-ejection.

export default defineConfig({
  logLevel: 'error',
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});
`;

export function transformViteConfig(files, changes) {
  if (!('vite.config.js' in files) && !('vite.config.ts' in files)) return;
  files['vite.config.js'] = CLEAN_VITE_CONFIG;
  delete files['vite.config.ts'];
  changes.push('Rewrote vite.config.js — dropped the @base44/vite-plugin call.');
}

// ---------- base44Client.js ----------

export function rewriteBase44Client(files, report, changes) {
  if (!report.base44Client.present) return;
  files['src/api/base44Client.js'] = readShimFile('base44Client.js');
  changes.push('Replaced the dead base44Client stub with a real re-export of the local runtime.');
}

// ---------- localDb shim + entity schemas ----------

export function injectLocalDbShim(files, report, changes) {
  files['src/lib/localDb.js'] = readShimFile('localDb.js');
  files['src/lib/_entitySchemas.generated.js'] = renderEntitySchemasModule(report);
  changes.push(
    `Injected src/lib/localDb.js (localStorage-backed) and _entitySchemas.generated.js with ${report.entities.length} entities.`,
  );
}

function renderEntitySchemasModule(report) {
  const schemas = Object.fromEntries(report.entities.map((e) => [e.name, e.schema]));
  return (
    '// Auto-generated by unvibe from the extractor entity schemas.\n' +
    '// Consumed by src/lib/localDb.js to build a typed local store.\n\n' +
    'export const entitySchemas = ' +
    JSON.stringify(schemas, null, 2) +
    ';\n'
  );
}

// ---------- src/api/entities.js ----------

export function injectEntitiesModule(files, report, changes) {
  if (report.entities.length === 0) return;
  const body =
    "// Generated by unvibe.\n" +
    "// Named exports for every entity the extractor discovered. Matches the\n" +
    "// import shape some Base44 apps use (`import { Card, Deck } from '@/api/entities'`).\n\n" +
    "import { entities } from '@/lib/localDb.js';\n\n" +
    report.entities
      .map((e) => `export const ${e.name} = entities.${e.name};`)
      .join('\n') +
    '\n';
  files['src/api/entities.js'] = body;
  changes.push(
    `Created src/api/entities.js with named exports for ${report.entities.length} entities.`,
  );
}

// ---------- app-params.js ----------

export function transformAppParams(files, changes) {
  const raw = readText(files['src/lib/app-params.js']);
  if (!raw) return;
  let next = raw;
  // Rename env vars VITE_BASE44_X → VITE_APP_X.
  next = next.replace(/\bVITE_BASE44_/g, 'VITE_APP_');
  // Strip the base44_ storage key prefix used for localStorage cache keys so
  // the ejected app isn't leaving breadcrumbs named after the old platform.
  next = next.replace(/base44_/g, 'app_');
  if (next !== raw) {
    files['src/lib/app-params.js'] = next;
    changes.push(
      'Rewrote src/lib/app-params.js to use VITE_APP_* env vars (was VITE_BASE44_*).',
    );
  }
}

// ---------- index.html ----------

export function transformIndexHtml(files, opts, changes) {
  const raw = readText(files['index.html']);
  if (!raw) return;
  // The extractor sometimes prepends a stray JS snippet before the `<!doctype>`
  // declaration; strip everything up to the first `<!doctype` or `<!DOCTYPE`.
  const doctypeIdx = raw.search(/<!doctype|<!DOCTYPE/);
  let next = doctypeIdx > 0 ? raw.slice(doctypeIdx) : raw;
  // Replace title.
  next = next.replace(
    /<title>[^<]*<\/title>/i,
    `<title>${escapeHtml(opts.projectName)}</title>`,
  );
  // Replace the Base44 favicon with a standard placeholder.
  next = next.replace(
    /<link rel="icon"[^>]*\/?>/i,
    '<link rel="icon" type="image/svg+xml" href="/favicon.svg" />',
  );
  if (next !== raw) {
    files['index.html'] = next;
    changes.push('Cleaned index.html — stripped extractor preamble, replaced title and favicon.');
  }
}

// ---------- README ----------

export function transformReadme(files, opts, report, changes) {
  files['README.md'] = renderReadme(opts, report);
  changes.push('Generated a fresh README.md with a clean quickstart.');
}

function renderReadme(opts, report) {
  const entitiesList = report.entities.length
    ? report.entities.map((e) => `- \`${e.name}\``).join('\n')
    : '- (none detected)';
  return `# ${opts.projectName}

This project was ejected from [Base44](https://base44.app) using [unvibe](https://github.com/gmall1/unvibe). It now runs fully on your own machine with no dependency on the Base44 platform.

## Quick start

\`\`\`bash
pnpm install
pnpm dev
\`\`\`

Then open the local URL Vite prints. All app data lives in your browser's \`localStorage\` under \`unvibe:db:v1\`.

## What changed vs. the raw Base44 export

- Removed \`@base44/sdk\` and \`@base44/vite-plugin\` dependencies.
- Rewrote \`vite.config.js\` to drop the Base44 build plugin.
- Replaced \`src/api/base44Client.js\` with a real re-export backed by a local store.
- Added \`src/lib/localDb.js\` — a schema-driven, localStorage-backed drop-in for the Base44 SDK surface (auth, entities, integrations).
- Renamed \`VITE_BASE44_*\` env vars to \`VITE_APP_*\`.

## Entities

This app was ejected with the following entities:

${entitiesList}

Their JSON schemas live in \`src/lib/_entitySchemas.generated.js\`. The runtime shim uses them to validate and persist records.

## Integrations

\`UploadFile\` works locally (returns a \`blob:\` URL). The other Base44 "Core" integrations — \`InvokeLLM\`, \`SendEmail\`, \`GenerateImage\`, \`SendSMS\` — throw a clear error explaining where to wire them up (\`src/api/integrations.js\`, once you add one). Each is a few lines with the provider of your choice (OpenAI, Resend, etc).

## Upgrading to a real backend

If you outgrow \`localStorage\`, replace the \`src/lib/localDb.js\` file with a thin adapter over your backend of choice (Supabase, Firebase, a FastAPI server, etc). Your source code does not need to change — it only talks to the \`db\` shape exported from \`localDb.js\`.

${report.malformedEntities.length > 0 || report.truncatedSourceFiles.length > 0 ? `## Notes from the eject

${report.malformedEntities.length > 0 ? `- The Base44 extractor produced truncated JSON for these entities: ${report.malformedEntities.map((m) => '`' + m.name + '`').join(', ')}. unvibe best-effort repaired the schemas — double-check them in \`src/lib/_entitySchemas.generated.js\` if you hit missing-field issues at runtime.
` : ''}${report.truncatedSourceFiles.length > 0 ? `- The extractor also appears to have **truncated these source files** mid-syntax. They will not build until the missing code is restored manually (look for unclosed JSX tags or braces at the end of each file):

${report.truncatedSourceFiles.map((t) => `  - \`${t.file}\` — ${t.reason}`).join('\n')}

  This is a known failure mode of third-party Base44 extractor extensions and is not something unvibe can auto-fix safely.
` : ''}
` : ''}## License

MIT. Do whatever you want with it.
`;
}

// ---------- .env.example ----------

export function generateEnvExample(files, report, changes) {
  const envVars = new Set(report.base44EnvVarReferences.map((v) => v.replace('VITE_BASE44_', 'VITE_APP_')));
  if (envVars.size === 0) return;
  const body =
    '# Generated by unvibe. These variables replace the Base44-branded ones\n' +
    '# the extractor left in the source code. Safe defaults included.\n\n' +
    [...envVars]
      .sort()
      .map((name) => `${name}=`)
      .join('\n') +
    '\n';
  files['.env.example'] = body;
  changes.push(`Generated .env.example with ${envVars.size} variable(s).`);
}

// ---------- helpers ----------

function inferProjectName(files) {
  try {
    const pkg = JSON.parse(readText(files['package.json']) ?? '{}');
    if (pkg.name && pkg.name !== 'base44-app') return pkg.name;
  } catch {
    // fall through
  }
  return 'Ejected App';
}

function inferProjectSlug(files) {
  return String(inferProjectName(files))
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'ejected-app';
}

function readText(entry) {
  if (entry == null) return null;
  if (typeof entry === 'string') return entry;
  if (entry instanceof Uint8Array || Buffer.isBuffer?.(entry)) {
    return Buffer.from(entry).toString('utf8');
  }
  return null;
}

function readShimFile(name) {
  return readFileSync(resolve(SHIM_ROOT, name), 'utf8');
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
